# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e33f9749b417a2f439bfcba3775f05c4b752c33e846e6e4a4cb52e144501cc36de0419841ab0f5800ca9f69adb94788b45ef603d04c717b01025e0d92f5fc2f6

test:
  secret_key_base: 7b7674c4cc78bcccbb80e49ce1c10a6e50e28e61c370ca1af515da688af5da801d5aa72704f6cfc0fe7deb3d7d538ff186d427bcfd4519c49e433c30eaf84a45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
